table '_Measure and Model Info'
	lineageTag: c297a8f3-dfa4-490a-82bf-6a72a75c0642

	measure 'Opportunities Created' = COUNTROWS(Opportunity)
		formatString: #,0
		lineageTag: 73c49aea-36d3-4f9d-be9b-090c6a2abba7

	measure 'Opportunities Closed' = ```
			
			    CALCULATE( 
			        [Opportunities Created], 
			        Opportunity[IsClosed] = TRUE, 
			        USERELATIONSHIP('Calendar'[Date], Opportunity[Opp Close Date_Simulated])
			        )
			```
		formatString: #,0
		lineageTag: 27707def-e9fa-4c3c-8bc8-ede12edd66cb

	measure 'Opportunities Won' = ```
			
			VAR og = 
			CALCULATE( 
			    [Opportunities Created], 
			        Opportunity[IsClosed] = TRUE, 
			        Opportunity[IsWon] = TRUE, 
			        USERELATIONSHIP('Calendar'[Date], Opportunity[Opp Close Date_Simulated])
			    )
			
			VAR new = 
			CALCULATE( 
			    [Opportunities Created], 
			    Opportunity[Opp Win Numeric] = 1, 
			    USERELATIONSHIP(Opportunity[Opp Close Date_Simulated], 'Calendar'[Date])
			    )
			
			RETURN new
			```
		formatString: 0
		lineageTag: a4d8e38b-9088-4994-a625-6ff1ff331235

	measure 'Opportunity Win Rate' = DIVIDE( [Opportunities Won], [Opportunities Closed])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: af11481a-88db-4407-96eb-ddffb183ec69

	measure 'Selected Descriptive Metric' = ```
			
			VAR metric = SELECTEDVALUE(Metrics[Metric]) 
			
			RETURN SWITCH(TRUE(), 
			metric = "Created", [Opportunities Created], 
			metric = "Closed", [Opportunities Closed],
			metric = "Won", [Opportunities Won],
			BLANK()
			)
			```
		formatString: 0
		lineageTag: 16361347-6195-474b-9bba-54479238dfc4

	measure 'Average Opportunity Lifecycle Days' = AVERAGE( Opportunity[Opp Lifecycle Days])
		lineageTag: 187f0b0a-670e-4bfb-93ec-1d5007fb85f3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Opportunities Lost' = [Opportunities Closed] - [Opportunities Won]
		formatString: 0
		lineageTag: 13a09574-1ff1-4bff-898b-93cbb82c78ae

	column Name
		displayFolder: _information columns
		lineageTag: 50a35730-9cad-48e4-b30e-7dc02dc32705
		summarizeBy: none
		isNameInferred
		sourceColumn: [Name]

		annotation SummarizationSetBy = Automatic

	column DisplayFolder
		displayFolder: _information columns
		lineageTag: 8ccc43a7-bdc3-402d-95ff-e3e400e3c789
		summarizeBy: none
		isNameInferred
		sourceColumn: [DisplayFolder]

		annotation SummarizationSetBy = Automatic

	column Table
		displayFolder: _information columns
		lineageTag: 04dbb8b7-976d-4c4b-8258-e44df7064fe6
		summarizeBy: none
		isNameInferred
		sourceColumn: [Table]

		annotation SummarizationSetBy = Automatic

	column DataType
		displayFolder: _information columns
		lineageTag: 7c34f1fd-bcc5-4cef-861a-f793d0aba89a
		summarizeBy: none
		isNameInferred
		sourceColumn: [DataType]

		annotation SummarizationSetBy = Automatic

	column DataCategory
		displayFolder: _information columns
		lineageTag: 8fd023fc-0fcf-405d-8aa6-d102d806d57d
		summarizeBy: none
		isNameInferred
		sourceColumn: [DataCategory]

		annotation SummarizationSetBy = Automatic

	column Description
		displayFolder: _information columns
		lineageTag: 1e515a82-3437-4a0d-8303-fe2f0f0a154b
		summarizeBy: none
		isNameInferred
		sourceColumn: [Description]

		annotation SummarizationSetBy = Automatic

	column Expression
		displayFolder: _information columns
		lineageTag: 9d8eebc3-6053-4e66-a863-b7964a109d15
		summarizeBy: none
		isNameInferred
		sourceColumn: [Expression]

		annotation SummarizationSetBy = Automatic

	column Segment
		displayFolder: _information columns
		lineageTag: 24211454-0f75-46d4-86e8-4a06174c0edc
		summarizeBy: none
		isNameInferred
		sourceColumn: [Segment]

		annotation SummarizationSetBy = Automatic

	partition '_Measure and Model Info' = calculated
		mode: import
		source = ```
				
				
				// create variables for each
				
				VAR mea = INFO.VIEW.MEASURES()
				VAR col = INFO.VIEW.COLUMNS()
				
				RETURN 
				
				// The segment column allows for a simple way to slice between measures and columns.
				
				UNION(
				// Combine the two tables into one
				ADDCOLUMNS( 
				    SUMMARIZE( mea, [Name], [DisplayFolder], [Table], [DataType], [DataCategory], [Description],[Expression]), "Segment", "Measures"),
				
				// TMDL + a simple prompt to write descriptions is a great task for Copilot (or other AI methods) 
				
				ADDCOLUMNS( 
				    SUMMARIZE( col, [Name], [DisplayFolder], [Table], [DataType], [DataCategory], [Description],[Expression]), "Segment", "Columns"))
				
				```

	annotation PBI_Id = de53d71b3d654290b555beb07f060e34

