table Contact
	lineageTag: 9d483d81-2552-4328-99b7-52c16ada599b

	column Id
		dataType: string
		lineageTag: 555f8881-b453-4e7e-9b67-97e423e495a0
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column IsDeleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 32ca52a5-f254-4971-9db8-4478650f8960
		summarizeBy: none
		sourceColumn: IsDeleted

		annotation SummarizationSetBy = Automatic

	column AccountId
		dataType: string
		lineageTag: 1a1fd8f8-589b-4287-a478-49ad5d4f8fc5
		summarizeBy: none
		sourceColumn: AccountId

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: f4f3f3f1-c35e-41a7-bd5c-cae23aef6eae
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: ec9bff76-5564-48ef-8845-b5c165776337
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: 811bebf2-4f46-48c6-9857-4dd2030df0fa
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column MobilePhone
		dataType: string
		lineageTag: 43d818e6-291c-4cca-9f84-6c104a10be5a
		summarizeBy: none
		sourceColumn: MobilePhone

		annotation SummarizationSetBy = Automatic

	column AssistantPhone
		dataType: string
		lineageTag: 4290f2d1-d379-4866-b77f-8a4dc2da8a6f
		summarizeBy: none
		sourceColumn: AssistantPhone

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 17107b27-6e62-4195-b5cc-653ff3663036
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 7e2dc3f6-83c9-4f68-bc50-61716e985746
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 1eee3213-1321-483a-b0c2-a362da626105
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column LeadSource
		dataType: string
		lineageTag: 8fbe16fe-9cd6-4411-b200-756bebd44be4
		summarizeBy: none
		sourceColumn: LeadSource

		annotation SummarizationSetBy = Automatic

	column LastActivityDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a335da68-a312-4857-b086-18cb6a25a24e
		summarizeBy: none
		sourceColumn: LastActivityDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EmailBouncedReason
		dataType: string
		lineageTag: 59df2619-fcf3-4db5-883a-62b847fadff2
		summarizeBy: none
		sourceColumn: EmailBouncedReason

		annotation SummarizationSetBy = Automatic

	column EmailBouncedDate
		dataType: string
		lineageTag: ac2b9247-7342-49a8-9035-bab3d049d092
		summarizeBy: none
		sourceColumn: EmailBouncedDate

		annotation SummarizationSetBy = Automatic

	column IsEmailBounced
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 95b6c8dc-561a-4b7b-9477-416b6c5c0394
		summarizeBy: none
		sourceColumn: IsEmailBounced

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 099418ab-15dd-4ac1-b777-83b36a1ea76a
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	partition Contact = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/earthfink1982/salesforce-in-powerbi/refs/heads/main/data/Contact.csv"),[Delimiter=",", Columns=17, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Id", type text}, {"IsDeleted", type logical}, {"AccountId", type text}, {"LastName", type text}, {"FirstName", type text}, {"Phone", type text}, {"MobilePhone", type text}, {"AssistantPhone", type text}, {"Email", type text}, {"Title", type text}, {"Department", type text}, {"LeadSource", type text}, {"LastActivityDate", type date}, {"EmailBouncedReason", type text}, {"EmailBouncedDate", type text}, {"IsEmailBounced", type logical}, {"Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

