table Metrics
	lineageTag: 20b6096e-9d98-4757-81af-9ac3b6e83929

	column Metric
		dataType: string
		lineageTag: f50113d9-76ef-4ca3-89ec-71db814d9442
		summarizeBy: none
		sourceColumn: Metric
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 126fdd4a-8738-42eb-b2f5-f39bc02fac09
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: string
		lineageTag: 3fcd848f-acc0-4706-acff-c3e73feea8cf
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition Metrics = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wci5KTSxJTVHSUXJJLU4uyiwoySxLBfIMlWJ1opXC8/MwZIzBMs45+cVYtBlBtGXmKQQBjQVJZyam5+UXl2QmAzlgSceydAWfzLTU5MrkHOwqglLLUvNKUxWw2W6iFBsLAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Metric = _t, Type = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Metric", type text}, {"Type", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

