table Opportunity
	lineageTag: 470e6957-0f6b-4d1b-9585-6d9da3743cce

	column Id
		dataType: string
		lineageTag: f56bae01-25bf-454c-b631-db1134397a70
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column AccountId
		dataType: string
		lineageTag: 5dc56623-1696-4d31-8d45-869c0d0bd37e
		summarizeBy: none
		sourceColumn: AccountId

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 77749641-21f4-4c81-8114-6266d6cc250e
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 68731974-d373-4e2a-9055-4c38fba798e4
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column StageName
		dataType: string
		lineageTag: 81d3bbed-45b3-4c23-8511-46f1dfa16784
		summarizeBy: none
		sourceColumn: StageName

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: int64
		formatString: 0
		lineageTag: 49f67e88-5c49-41d0-93d5-20e7a6c6f7cc
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column ExpectedRevenue
		dataType: int64
		formatString: 0
		lineageTag: c97a865e-aa78-461b-a8ba-44f5d1049080
		summarizeBy: sum
		sourceColumn: ExpectedRevenue

		annotation SummarizationSetBy = Automatic

	column LeadSource
		dataType: string
		lineageTag: 5376bc2c-3860-41a3-a543-41bbddc88a90
		summarizeBy: none
		sourceColumn: LeadSource

		annotation SummarizationSetBy = Automatic

	column IsClosed
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e673d500-cef6-4f7f-89c4-7a89c5580313
		summarizeBy: none
		sourceColumn: IsClosed

		annotation SummarizationSetBy = Automatic

	column IsWon
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4e786a09-22a5-40f8-8a8e-dab073b4153f
		summarizeBy: none
		sourceColumn: IsWon

		annotation SummarizationSetBy = Automatic

	column 'Opp Creation Date_Simulated'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7e1206e3-1e4f-44db-a4b5-1cda937eb8f6
		summarizeBy: none
		sourceColumn: Opp Creation Date_Simulated

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Opp Close Date_Simulated'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 1561ea72-583c-4be5-8ff2-f6d22504b400
		summarizeBy: none
		sourceColumn: Opp Close Date_Simulated

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Opp Lifecycle Days'
		dataType: int64
		formatString: 0
		lineageTag: 6d09af0a-5b88-41e0-98e7-2831c6036bcb
		summarizeBy: sum
		sourceColumn: Opp Lifecycle Days

		annotation SummarizationSetBy = Automatic

	column 'Opp Win Numeric'
		dataType: int64
		formatString: 0
		lineageTag: d8356d69-22ff-4a9b-a995-a46689ece11c
		summarizeBy: sum
		sourceColumn: Opp Win Numeric

		annotation SummarizationSetBy = Automatic

	partition Opportunity = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/earthfink1982/salesforce-in-powerbi/refs/heads/main/data/Opportunity.csv"),[Delimiter=",", Columns=19, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Id", type text}, {"AccountId", type text}, {"Name", type text}, {"Description", type text}, {"StageName", type text}, {"Amount", Int64.Type}, {"Probability", Int64.Type}, {"ExpectedRevenue", Int64.Type}, {"CloseDate", type date}, {"NextStep", type text}, {"LeadSource", type text}, {"IsClosed", type logical}, {"IsWon", type logical}, {"CreatedDate", type date}, {"LastModifiedDate", type datetime}, {"LastActivityDate", type date}, {"Opportunity Lifecycle (Days)", Int64.Type}, {"Opp Creation Date_Simulated", type date}, {"Opp Close Date_Simulated", type date}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Id", "AccountId", "Name", "Description", "StageName", "Amount", "ExpectedRevenue", "LeadSource", "IsClosed", "IsWon", "Opp Creation Date_Simulated", "Opp Close Date_Simulated"}),
				    #"Opp Lifecycle Days" = Table.AddColumn(#"Removed Other Columns", "Opp Lifecycle Days", each if [Opp Creation Date_Simulated] = null then null else if [Opp Close Date_Simulated] = null then Duration.Days( DateTime.FixedLocalNow() - [Opp Creation Date_Simulated]) else Duration.Days([Opp Close Date_Simulated] - [Opp Creation Date_Simulated]), Int64.Type),
				    #"Opp Win Numeric" = Table.AddColumn(#"Opp Lifecycle Days", "Opp Win Numeric", each if [IsClosed] = true and [IsWon] = true then 1 else if [IsClosed] = true then 0 else null, Int64.Type)
				in
				    #"Opp Win Numeric"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

